title:              La llumanera
email:              jordimarias@gmail.com
description:        Blog personal d'en Jordi Marias Parella
author:             Jordi Marias Parella
baseurl:            "/personal"
url:                "jordimarias.com"

# Social Profiles
twitter_username:   SirMarias
github_username:    JordiMarias
#facebook_username:  StartBootstrap
instagram_username:  jordi_marias
linkedin_username:   jordi-marias-parella-019a0616a

locale: ca
# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
